### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by Puyodead1** [Tslat/Passive-Mobs#1]
Hello, 
I have forked this project and updated it to 1.18, and as the current license allows redistribution, I listed it on [modrinth.com](https://modrinth.com/mod/passivemobs18) (giving proper credit of course) so that others who may not be able to compile it on their own can use it. The problem is that the current license is not valid for a Minecraft mod due to the strict definition set out for non-free programs. It does not allow non-free dependencies, which Minecraft is. I would like to request the license be changed, or with your permission, allow me to change it in my fork to LGPLv3, which is similar to and based off of the GPLv3 but does not have this same restriction and is therefore valid for a Minecraft mod.

Thank you!

**Comment by Tslat** [comment]
I'm fine with changing my license to be more permissive, I'll let you know

IF you've forked and ported to 1.18.2, I could make a branch for that if you want to PR your changes back?
Can upload it to Curseforge then too

**Comment by Puyodead1** [comment]
> I'm fine with changing my license to be more permissive, I'll let you know
> 
> IF you've forked and ported to 1.18.2, I could make a branch for that if you want to PR your changes back? Can upload it to Curseforge then too

Sure, I can do that tomorrow.

**Comment by Puyodead1** [comment]
Thank you!
