### ISSUE TITLE
Help with datapacks

### ISSUE THREAD

**Issue by AlphystheNerd** [Tslat/Passive-Mobs#11]
I'm trying to make a datapack for 1.21 with this mod to make cave spiders immune to the pacification but it hasn't been working. Is there something I'm doing wrong?

![Screenshot 2024-11-28 104450](https://github.com/user-attachments/assets/fb1f6095-abd4-43a1-a858-e22446753e26)

This is what I have so far.

**Comment by Tslat** [comment]
it's in the `tslatentitystatus` namespace, not `c`
