### ISSUE TITLE
Passive Mobs Fabric 1.20-1.3.1 reports not compatible with MC 1.20.1

### ISSUE THREAD

**Issue by Tursiops-G** [Tslat/Passive-Mobs#4]
Needs Dependency listing (fabric.mod.json) updated to accomodate MC Version 1.20.1

**Comment by Tslat** [comment]
Sigh

**Comment by Tursiops-G** [comment]
?? Is advertised as compatible on Modrinth...

**Comment by Tslat** [comment]
Yeah I know
Is all good, I'll fix it lol
