### ISSUE TITLE
Suggestion: Passive Hostile Mobs Run Away Setting

### ISSUE THREAD

**Issue by coldReactive** [Tslat/Passive-Mobs#5]
I'd like to suggest there be a tag or setting that allows the mod to dictate if the passive hostile mobs will run away from the player when attacked, as if they were animals. Unless this is already part of how your mod works? As it wasn't explicitly explained on the Mod Page.

**Comment by Tslat** [comment]
That's more or less outside the scope of the mod, to be fair

It's just meant to be an easy drop-in mod to make mobs peaceful
Altering their actual AI and stuff is a whole other ballgame which isnt really what I aimed to do
