### ISSUE TITLE
Piglin id on fabric 1.20.6

### ISSUE THREAD

**Issue by DaFtuf** [Tslat/Passive-Mobs#9]
![Desktop Screenshot 2024 06 27 - 17 04 00 04](https://github.com/Tslat/Passive-Mobs/assets/106696538/070fc78f-fb85-45a1-be89-6ecfc74df89a)
Piglin id doesn't seem to work in data pack tags on fabric 1.20.6, even though other mobs id work

**Comment by DaFtuf** [comment]
actually breeze id don't work either, and probably some others too. i don't know why but i can tell for sure that skeleton, zombie, zombified piglin, slime, creeper, evoker and some others are hostile.

**Comment by Tslat** [comment]
Yeah anything using brains can't use that tag, because brains don't keep a reference to their owner =/
This is stated on the mod pages on CF/Modrinth

There's not a lot I can do here without being it unreliable
